## NumPy

In [1]:
import numpy as np

### np.array

In [2]:
l = [1, 2, 3, 4, 5]

In [4]:
npa = np.array(l)

In [5]:
type(l), type(npa)

(list, numpy.ndarray)

In [6]:
npa.shape

(5,)

In [10]:
l.append('string')
l

[1, 2, 3, 4, 5, 6, 'string']

In [11]:
npa = np.array(l)

In [12]:
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [13]:
l1 = [1, 4, 9, 16]

In [14]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [15]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 1, 4, 9, 16]

In [16]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', '6', 'string', '1', '4', '9', '16'],
      dtype='<U11')

In [17]:
l + [20]

[1, 2, 3, 4, 5, 6, 'string', 20]

In [19]:
l = [[1, 2], [3, 4], [3, 4]]
l, type(l)

([[1, 2], [3, 4], [3, 4]], list)

In [20]:
npa2d = np.array(l)

In [22]:
npa2d, type(npa2d)

(array([[1, 2],
        [3, 4],
        [3, 4]]),
 numpy.ndarray)

In [23]:
npa2d.shape

(3, 2)

In [24]:
npa2d = np.array(l, dtype = 'float')

In [25]:
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [27]:
type(npa2d)

numpy.ndarray

In [28]:
npa2d = np.array(l, dtype = 'int')

In [29]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [31]:
npa2d = npa2d.astype('str')

In [32]:
npa2d[0][0]

'1'

In [33]:
npa2d[0][0] + str(1)

'11'

## np.nan and np.inf

In [34]:
np.nan

nan

In [35]:
np.nan == np.nan

False

In [37]:
None == None

True

In [38]:
np.inf == np.inf

True

In [40]:
npa2d = npa2d.astype('int')

In [41]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [43]:
npa2d = npa2d.astype('float')
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [44]:
npa2d = npa2d.astype('str')
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

In [46]:
npa2d = npa2d.astype('float')
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [47]:
npa2d = npa2d.astype('int')
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [51]:
npa2d = npa2d.astype('float')
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [52]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf

In [53]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 3.,  4.]])

In [54]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [55]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [57]:
flag = np.isnan(npa2d) | np.isinf(npa2d)

In [58]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [59]:
npa2d[flag]

array([nan, inf])

In [60]:
npa2d[flag] = 0

In [61]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Statistical Operations

In [62]:
# mean, var, std, med

In [63]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [65]:
npa2d.mean()

2.0

In [66]:
npa2d.min()

0.0

In [67]:
npa2d.max()

4.0

In [68]:
npa2d.var()

2.3333333333333335

In [69]:
npa2d.std()

1.5275252316519468

In [71]:
np.median(npa2d)

2.5

## Shape(), Reshape(), Ravel()

In [72]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [73]:
npa2d.shape

(3, 2)

In [78]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 3., 4.]])

In [80]:
npa2d.reshape(2, 3).ravel()

array([0., 2., 3., 0., 3., 4.])

In [82]:
npa2d.ravel()

array([0., 2., 3., 0., 3., 4.])

In [83]:
npa2d.flatten()

array([0., 2., 3., 0., 3., 4.])

## sequence, repetitions, and random numbers

### arange(), linspace(), random(), zeros(), and ones()

In [84]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [85]:
np.arange(1, 5, dtype = 'float')

array([1., 2., 3., 4.])

In [87]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [92]:
np.linspace(1, 20, 6)

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [93]:
np.logspace(1, 20, 6)

array([1.00000000e+01, 6.30957344e+04, 3.98107171e+08, 2.51188643e+12,
       1.58489319e+16, 1.00000000e+20])

In [99]:
np.zeros([1,5])

array([[0., 0., 0., 0., 0.]])

In [101]:
np.zeros([1, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [103]:
np.ones([1, 2])

array([[1., 1.]])

In [107]:
np.tile([1, 2], 3)

array([1, 2, 1, 2, 1, 2])

In [110]:
np.repeat([1, 2], 3)

array([1, 1, 1, 2, 2, 2])

In [112]:
np.random.rand(3, 3)

array([[0.00877059, 0.33168115, 0.31817576],
       [0.12034717, 0.71519728, 0.37126276],
       [0.56240372, 0.8303584 , 0.16396384]])

In [117]:
np.random.randint(0, 100, [3, 3])

array([[19, 52,  5],
       [67, 95, 63],
       [23, 10, 97]])

In [120]:
np.random.seed(1)
np.random.randint(0, 100, [3, 3])

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

In [123]:
np.unique(npa2d)

array([0., 2., 3., 4.])

In [124]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [125]:
np.unique(npa2d, return_counts=True)

(array([0., 2., 3., 4.]), array([2, 1, 2, 1], dtype=int64))

## Where()

In [126]:
arr = np.array([8,94,8,56,1,3,4,5,7])

In [127]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [128]:
np.where(arr>10)

(array([1, 3], dtype=int64),)

In [129]:
index = np.where(arr>10)
arr[index]

array([94, 56])

In [130]:
index = np.where(arr<10)
arr[index]

array([8, 8, 1, 3, 4, 5, 7])

In [133]:
index = np.where(arr==8)
arr[index]

array([8, 8])

In [136]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [137]:
arr[arr>10]

array([94, 56])

In [138]:
arr.max()

94

In [142]:
arr.argmax(), arr.argmin()

(1, 4)

In [143]:
arr[arr.argmin()]

1

## File read and Write

In [144]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [145]:
np.savetxt('npa2dtest.csv', npa2d, delimiter=',')

In [146]:
np.loadtxt('npa2dtest.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [147]:
np.save('data.npy', npa2d)

In [148]:
np.load('data.npy')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [151]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [155]:
np.savez('both.npz', arr, npa2d)

In [156]:
np.load('both.npz')

In [157]:
np.load('both.npz').files

['arr_0', 'arr_1']

In [158]:
d = np.load('both.npz')

In [159]:
d.files

['arr_0', 'arr_1']

In [161]:
d[d.files[0]]

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

## Comcatenate and Sorting

In [162]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [166]:
np.concatenate([npa2d, npa2d], axis=0)

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [167]:
np.concatenate([npa2d, npa2d], axis=1)

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [171]:
arr.shape, npa2d.shape

((9,), (3, 2))

In [172]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [174]:
npa = np.hstack([npa2d, npa2d])

In [176]:
npa.sort()

In [177]:
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

## Working with Dates

In [178]:
d = np.datetime64('2020-12-01 23:34:23')

In [179]:
d

numpy.datetime64('2020-12-01T23:34:23')

In [180]:
d + 10

numpy.datetime64('2020-12-01T23:34:33')

In [181]:
oneday = np.timedelta64(1, 'D')

In [182]:
oneday

numpy.timedelta64(1,'D')

In [183]:
d + oneday

numpy.datetime64('2020-12-02T23:34:23')

In [184]:
oneminute = np.timedelta64(1, 'm')

In [185]:
d + oneminute

numpy.datetime64('2020-12-01T23:35:23')

In [186]:
oneweek = np.timedelta64(1, 'W')

In [187]:
d + oneweek

numpy.datetime64('2020-12-08T23:34:23')

In [ ]:
np.append()